trigger: 
  -
    mode: http
    disable: true
    setting:
      port: 8088

filter:
  -
    mode: json
    setting:
      addmetadata: 
        throttlekey: "[id]"   
        providerid: "[providerid]" 
        emailsubject: "[email][subject]"
        emailbody: "[email][body]"
  -
    mode: throttle
    setting:
      triggercount: 2
      actioncount: 2
      periodsecond: 10
      key: "%{throttlekey}"
  -
    mode: mysql
    setting:
      ip: 
      user: 
      password: 
      database: 
      command: "select URI from usercontact where FK_User = '%{providerid}'"
      addmetadata:
        emailaddress: "[URI]"
      cache:
        cachekey: "%{providerid}"
        timeoutsecond: 20

action:
  - 
    mode: email
    setting:
      address: smtp.gmail.com
      port: 587
      username: 
      password: 
      from: 
      staticto: 
      dynamicto: "%{emailaddress}"
      subject: "test %{emailsubject}"
      body: "test %{emailbody}"
  -
    mode: line
    setting:
      accesstoken: 
      message: "test line %{emailbody}"
