trigger: 
  -
    mode: udp
    setting:
      port: 8088
  -
    mode: http
    setting:
      port: 8088

filter:
  -
    mode: json
    setting:
      addmetadata: 
        throttlekey: "[ID]"
        level: "[Data][Level]"
        timestamp: "[Data][Timestamp]"
        step: "[Data][JobStep]"
        transtype: "[Data][LogType]"
        datatype: "[Data][DataType]"
        datatarget: "[Data][Target]"        
        provider: "[Data][Provider]"
        authority: "[Data][Authority]"
        operation: "[Data][Operation]"
        operationresult: "[Data][Status]"
        message: "[Data][Message]"
        detail: "[Data][ExceptionStackTrace]"
  -
    mode: throttle
    setting:
      triggercount: 2
      actioncount: 2
      periodsecond: 10
      key: "%{throttlekey}"

action:
  - 
    mode: email
    setting:
      address: smtp.gmail.com
      port: 587
      username: pplovable@gmail.com
      password: daulogr2
      from: pplovable@gmail.com
      staticto: [tl.yu@iisigroup.com]
      subject: "PTX ETL Notification - %{transtype} - %{datatarget} - %{datatype}"
      body: " \r\n 時間:%{timestamp}\r\n
              等級:%{level}\r\n\r\n
              ==========ETL==========\r\n
              步驟:%{step}\r\n
              執行動作:%{operation}\r\n
              執行動作結果:%{operationresult}\r\n\r\n
              ==========Data==========\r\n
              運具:%{transtype}\r\n
              種類:%{datatarget}\r\n
              性質:%{datatype}\r\n
              提供者:%{provider}\r\n
              業管機關:%{authority}\r\n\r\n
              ==========Debug==========\r\n
              訊息:%{message}\r\n
              詳細訊息:%{detail}\r\n"
  -
    mode: line
    setting:
      #accesstoken: 2mJC8j7b1fdb6VnUISau31gsJdQWsjeoJ5mV48tnBoZ  #test
      accesstoken: hqtY0bXbrDgLh7jNmPCjvrr6EdBvh8hkz0udJLbGFWl   #ptx
      message: "\r\n 時間:%{timestamp}\r\n
                等級:%{level}\r\n\r\n
                ==========ETL==========\r\n
                步驟:%{step}\r\n
                執行動作:%{operation}\r\n
                執行動作結果:%{operationresult}\r\n\r\n
                ==========Data==========\r\n
                運具:%{transtype}\r\n
                種類:%{datatarget}\r\n
                性質:%{datatype}\r\n
                提供者:%{provider}\r\n
                業管機關:%{authority}\r\n\r\n"
