trigger: 
  mode: udp
  setting:
    port: 8088

filter:
  -
    mode: json
    setting:
      addmetadata: 
        throttlekey: "[id]"   
        providerid: "[providerid]" 
        emailsubject: "[email][subject]"
        emailbody: "[email][body]"
  -
    mode: throttle
    setting:
      triggercount: 2
      actioncount: 2
      periodsecond: 10
      key: "%{throttlekey}"

action:
  - 
    mode: email
    setting:
      address: smtp.gmail.com
      port: 587
      username: pplovable@gmail.com
      password: daulogr2
      from: pplovable@gmail.com
      staticto: [tl.yu@iisigroup.com]
      subject: "test %{emailsubject}"
      body: "test %{emailbody}"
  -
    mode: line
    setting:
      accesstoken: 2mJC8j7b1fdb6VnUISau31gsJdQWsjeoJ5mV48tnBoZ
      message: "test line %{emailbody}"
