trigger: 
  mode: http
  setting:
    port: 8089

action:
  - 
    mode: email
    setting:
      address: smtp.gmail.com
      port: 587
      username: pplovable@gmail.com
      password: 
      from: pplovable@gmail.com
      to: [tl.yu@iisigroup.com]
      subject: "test %{subject}"
      body: "test %{body}"
