trigger: 
  mode: http
  setting:
    port: 8088

filter:
  -
    mode: json
    setting:
      addmetadata: 
        key: "[key]"
        test: "[level1][level2][test2]"
  -
    mode: throttle
    setting:
        triggercount: 2
        actioncount: 2
        periodsecond: 10
        key: "%{key}"

action:
  - 
    mode: email
    setting:
      address: smtp.gmail.com
      port: 587
      username: pplovable@gmail.com
      password: 
      from: pplovable@gmail.com
      to: [tl.yu@iisigroup.com]
      subject: "test %{subject}"
      body: "test %{body}"
