trigger:   
  mode: swaggerstats
  setting: 
    swagger_url: https://ptx.transportdata.tw/motc/api/main/docs/v2
    api_ip: https://ptx.transportdata.tw
    api_path: MOTC/
    skp_operations: [op1, op2]
    operations: 
       - 
        operationid: op3
        condition: hasvalue
        fields: [routeId, busId]
       - 
        operationid: op4
        condition: gap
        fields: [srcupdatetime, sysupdatetime]
        thresholdtype: minute 
        threshold: 5

action:
  - 
    mode: email
    setting:
      address: smtp.gmail.com
      port: 587
      username: pplovable@gmail.com
      password: 
      from: pplovable@gmail.com
      to: [tl.yu@iisigroup.com]
      subject: "test %{subject}"
      body: "test %{body}"
    throttlingpolicy:
        mode: actionlimitation
        setting:
          second: 5
          limitation: 2
