trigger:   
  mode: swaggerstats
  setting: 
    swagger_url: https://ptx.transportdata.tw/motc/api/main/docs/v2
    api_ip: https://ptx.transportdata.tw
    api_path: MOTC/
    skip_operations: [op1, op2]
    operations: 
       - 
        operationid: op3
        condition: hasvalue
        fields: [routeId, busId]
       - 
        operationid: op4
        condition: gap
        fields: [srcupdatetime, sysupdatetime]
        thresholdtype: minute 
        threshold: 5