trigger: 
  - 
    mode: swaggerstats
    setting: 
      swagger_url: https://ptx.transportdata.tw/motc/api/main/docs/v2
      api_ip: https://ptx.transportdata.tw
      api_path: MOTC/
      operations: 
        - 
          operationid: con1
          condition: hasvalue
          fields: ["routeId", "busId"]
        - 
          operationid: con2
          condition: gap
          fields: ["srcupdatetime", "sysupdatetime"]
          thresholdtype: minute 
          threshold: 5
  - 
    mode: http
    setting:
      port: 8080
  -
    mode: http
    setting:
      port: 8081

action:
  - 
    mode: email
    setting:
      address: smtp.gmail.com
      port: 587
      username: pplovable@gmail.com
      password: daulogr2
      from: pplovable@gmail.com
      to: tl.yu@iisigroup.com
      subject: "test %{subject}"
      body: "test %{body}"
    policy:
        mode: alwaysfired
        setting:
  
